apiVersion: v1
kind: ConfigMap
metadata:
  name: dms-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/dms"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  CASSANDRA_CONTACT_POINTS: "cassandra-service"
  APP_S3_ENDPOINT: "http://minio-service:9000"
  APP_S3_REGION: "us-east-1"
  APP_S3_BUCKET: "dms-bucket"
